services:
  - type: web
    name: gestion-events-laravel
    runtime: php
    plan: free
    buildCommand: |
      composer install --no-interaction --prefer-dist --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://gestion-events-laravel.onrender.com
      - key: DB_CONNECTION
        value: sqlite
