services:
  - type: web
    name: laravel-app
    env: docker
    buildCommand: docker build -t laravel-app .
    startCommand: docker run -d -p 80:80 laravel-app
    envVars:
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql.railway.internal
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: pxBcprlOMGPNTxkRSsvwLjPlcWAluuAo
      #utilisation de railway et ses variables